version: "3.9"

services:
  postgres:
    build: ./postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: pesquisa_satisfacao
    ports:
      - "5432:5432"
    networks:
      - devnet

  mongodb:
    build: ./mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    networks:
      - devnet

  node-app:
    build: ./node
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    networks:
      - devnet
    volumes:
      - ./node:/app
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017

networks:
  devnet:
    driver: bridge